chore: use env to start or not adsbexchange (aboid error at startup)

diff --git a/root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/script b/root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/script
--- a/root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/script
+++ b/root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/script
@@ -1,24 +1,21 @@
 #!/command/with-contenv bash
 
 SERVICE_ENABLE_ADSBEXCHANGE=${SERVICE_ENABLE_ADSBEXCHANGE:-false}
+if [ "$SERVICE_ENABLE_ADSBEXCHANGE" != "false" ]; then
+    if ((${#ADSBEXCHANGE_UUID} == 36)); then
+        set -eo pipefail
 
-if [ "$SERVICE_ENABLE_ADSBEXCHANGE" == "false" ]; then
-    exit 1
-fi
+        echo "${ADSBEXCHANGE_UUID}" >/usr/local/share/adsbexchange/adsbx-uuid
+        mkdir -p /run/adsbexchange-stats
+        mkdir -p /run/adsbexchange-feed
 
-if (( ${#ADSBEXCHANGE_UUID} == 36 )); then
-    set -eo pipefail
-
-    echo "${ADSBEXCHANGE_UUID}" > /usr/local/share/adsbexchange/adsbx-uuid
-    mkdir -p /run/adsbexchange-stats
-    mkdir -p /run/adsbexchange-feed
-
-    # delay other adsbexchange services a little bit to produce less error messages on startup
-    sleep 1.5
-else
-    for i in {1..5}; do
-        echo "FATAL: ADSB_EXCHANGE_UUID not set or invalid!" | mawk -W interactive '{printf "%c[32m[adsbexchange-conf]%c[31m %s\n", 27, 27, $0}'
-    done
-    kill 1
-    exit 1
+        # delay other adsbexchange services a little bit to produce less error messages on startup
+        sleep 1.5
+    else
+        for i in {1..5}; do
+            echo "FATAL: ADSB_EXCHANGE_UUID not set or invalid!" | mawk -W interactive '{printf "%c[35m[adsbexchange-conf]%c[31m %s\n", 27, 27, $0}'
+        done
+        kill 1
+        exit 1
+    fi
 fi
